In [7]:
import pandas as pd
import numpy as np
import os

from scipy.stats import pearsonr
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [8]:
def perform_metrics(y_truth, y_forecasted): 

    mae = round(mean_absolute_error(y_truth, y_forecasted) ,8)
    mape = round(np.mean(np.abs((y_truth - y_forecasted) / y_truth)) * 100, 8)
    mse = round(mean_squared_error(y_truth, y_forecasted), 8)
    rmse = round(mse**(0.5), 8)
    rmspe = round((np.sqrt(np.mean(np.square((y_truth - y_forecasted) / y_truth)))) * 100, 8)
    r2 = round(r2_score(y_truth, y_forecasted), 8)
    try:
        corr, _ = pearsonr(y_truth, y_forecasted)
        pearson = round(corr, 8)
    except:
        pearson = None

    return mae, mape, mse, rmse, rmspe, r2, pearson

In [9]:
list_files = os.listdir('/home/ricardo/Documents/tcc_files/TCC/tcc_scripts_notebook/datasets/train_test')
list_files

['test_ma_1d.csv',
 'test_naive_1h.csv',
 'test_prophet_1h.csv',
 'test_lstm_1h.csv',
 'gridcv',
 'test_es_1d.csv',
 'test_es_1h.csv',
 'test_ar_1d.csv',
 'test_lstm_1d.csv',
 'test_arima_1d.csv',
 'test_naive_1d.csv',
 'test_arima_1h.csv',
 'train_lstm_1d.csv',
 'test_prophet_1d.csv',
 'test_ar_1h.csv',
 'test_ma_1h.csv']

In [10]:
best_params = {
    'test_ma_1d.csv': {'p_order': 0, 'd_order': 1, 'q_order': 5},
    'test_ma_1h.csv': {'p_order': 0, 'd_order': 1, 'q_order': 2},
    'test_naive_1h.csv': {None},
    'test_naive_1d.csv': {None},
    'test_prophet_1h.csv': {'diff_order': 1},
    'test_prophet_1d.csv': {'diff_order': 1},
    'test_es_1d.csv': {'alpha': 0.9},
    'test_es_1h.csv': {'alpha': 0.9},
    'test_ar_1d.csv': {'p_order': 5, 'd_order': 1, 'q_order': 0},
    'test_ar_1h.csv': {'p_order': 4, 'd_order': 1, 'q_order': 0},
    'test_arima_1d.csv': {'p_order': 5, 'd_order': 0, 'q_order': 4},
    'test_arima_1h.csv': {'p_order': 4, 'd_order': 1, 'q_order': 3},
    'test_lstm_1d.csv': {'batch_size': 5, 'num_units': 50, 'epochs': 200},
    'test_lstm_1h.csv': {'batch_size': 100, 'num_units': 100, 'epochs': 200},
}

data = {
    'model': [],
    'periodicity': [],
    'best_params': [],
    'mae': [],
    'mape': [],
    'mse': [],
    'rmse': [],
    'rmspe': [],
    'r2': [],
    'pearson': []
}

list_files = os.listdir('/home/ricardo/Documents/tcc_files/TCC/tcc_scripts_notebook/datasets/train_test')

for file in list_files:
    
    file_aux = file.split('_')
    
    if file_aux[0] == 'test':
        
        df_aux = pd.read_csv('/home/ricardo/Documents/tcc_files/TCC/tcc_scripts_notebook/datasets/train_test/'+file, sep = '\t')
        
        mae, mape, mse, rmse, rmspe, r2, pearson = perform_metrics(df_aux['y_test'], df_aux['y_test_predict'])
        
        model = file_aux[1].upper()
        periodicity = file_aux[2].split('.')[0].upper()

        data['model'].append(model)
        data['periodicity'].append(periodicity)
        data['best_params'].append(best_params[file])
        data['mae'].append(mae)
        data['mape'].append(mape)
        data['mse'].append(mse)
        data['rmse'].append(rmse)
        data['rmspe'].append(rmspe)
        data['r2'].append(r2)
        data['pearson'].append(pearson)
        
df_metrics = pd.DataFrame(data).sort_values(by=['model']).reset_index(drop = True)

In [16]:
df_metrics.sort_values(by=['rmspe']).reset_index(drop = True)

,model,periodicity,best_params,mae,mape,mse,rmse,rmspe,r2,pearson
0,ES,1H,{'alpha': 0.9},43.852720,0.504440,6859.607090,82.822745,1.003895,0.996993,0.998496
1,MA,1H,"{'p_order': 0, 'd_order': 1, 'q_order': 2}",43.868567,0.504552,6861.359727,82.833325,1.006454,0.996992,0.998496
2,AR,1H,"{'p_order': 4, 'd_order': 1, 'q_order': 0}",43.882605,0.504669,6864.998386,82.855286,1.006695,0.996990,0.998495
3,ARIMA,1H,"{'p_order': 4, 'd_order': 1, 'q_order': 3}",43.911293,0.505064,6866.378491,82.863614,1.007048,0.996990,0.998495
4,NAIVE,1H,{None},43.994821,0.505847,6889.263706,83.001589,1.008511,0.996980,0.998490
5,PROPHET,1H,{'diff_order': 1},44.007770,0.506162,6895.603131,83.039768,1.008912,0.996977,0.998490
6,LSTM,1H,"{'batch_size': 100, 'num_units': 100, 'epochs'...",46.918214,0.544529,7178.508278,84.726078,1.036555,0.996853,0.998467
7,ES,1D,{'alpha': 0.9},255.077518,2.949796,158088.917152,397.603970,5.274222,0.931058,0.965375
8,NAIVE,1D,{None},257.277212,2.977890,160702.241901,400.876841,5.326645,0.929918,0.964917
9,PROPHET,1D,{'diff_order': 1},262.585297,3.044043,164085.305067,405.074444,5.336425,0.928443,0.964543
10,LSTM,1D,"{'batch_size': 5, 'num_units': 50, 'epochs': 200}",263.481613,3.051155,162799.961875,403.484773,5.353380,0.929003,0.965129
11,MA,1D,"{'p_order': 0, 'd_order': 1, 'q_order': 5}",263.208363,3.054665,166762.460951,408.365597,5.434174,0.927275,0.963732
12,AR,1D,"{'p_order': 5, 'd_order': 1, 'q_order': 0}",263.813722,3.061769,167332.619756,409.063100,5.441015,0.927027,0.963648
13,ARIMA,1D,"{'p_order': 5, 'd_order': 0, 'q_order': 4}",269.006682,3.109067,169798.601484,412.066259,5.444784,0.925951,0.962996